[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.8"
rand = "0.8.5"
thiserror = "1.0.60"
aes-gcm = "0.10.3"
hex = "0.4.3"
chrono = "0.4.38"
